<?php

// $Id$

/**
 * @file
 * Implementation of http:BL for Drupal. It provides IP-based blacklisting
 * through http:BL and allows linking to a honeypot.
 *
 * @author Mark Janssen
 * @link http://ceaseless.ws/httpbl
 * @link http://httpbl.org/
 */
 
/**
 * 
 * Version 0.9, 18/05/2007
 * Contact: praseodym (at) gmail (dot) com
 *
 * Feel free to improve this module, but please contact the author with any
 * changes you make so they can be implemented into the 'official' version.
 * 
 * Changelog:
 * 
 * - v0.1, 28/04: Initial version
 * - v0.2, 28/04: Search engines should no longer be blocked
 * - v0.3, 29/04: Added option to add a honeypot link
 * - v0.4, 29/04: Test access key on form submit
 * - v0.5, 29/04: Option to add honeypot link to the footer of every page
 * - v0.6, 29/04: Logging options
 * - v0.7, 29/04: Fixed problems with Drupal page caching,
 *                fancied up settings page (thanks to alienbrain)
 * - v0.8, 30/04: Added blacklist status caching (thanks to dikini)
 *         01/05: Customization of ban message
 *         01/05: Whitelisting through user.module
 * - v0.9, 17/05: Greylisting with automatic session whitelisting
 *
 * Ideas/todo:
 *
 * - Include a honeypot with the module
 * - Search engine identification (needs data from http:BL guys)
 *
 * Todo for 'comment, registration and contact forms'-mode:
 * - Clear cache on settings submit
 * - Hook into forms
 * - Avoid cache (results might be too old)
 *
 */
 
/**
 * Implementation of hook_init.
 */
function httpbl_init() {
  // Testcases at http://www.projecthoneypot.org/httpbl_api.php
  // $ip = '127.1.80.1';
  $ip = $_SERVER['REMOTE_ADDR'];
  $iplink = 'http://www.projecthoneypot.org/search_ip.php?ip=' . $ip;

  if (variable_get('httpbl_check', 0) != 2) {
    return;
  }
  
  $blacklisted = httpbl_blacklisted($ip);
  
  if ($blacklisted === 2 && !$_SESSION['httpbl_whitelisted'] && $_GET['q'] != 'httpbl/whitelist') {
    // greylisted
    $message = variable_get('httpbl_message_grey', "Sorry, %ip has been greylisted by <a href=\"%ipurl\">http:BL</a>.\nYou may try whitelisting on <a href=\"%whitelisturl\">%whitelisturl</a>.\n%honeypot");
    if ($link = variable_get('httpbl_link', NULL)) {
      $word = variable_get('httpbl_word', 'randomness');
      $link = httpbl_honeylink($link, $word);
    }
    
    $message = strtr($message, array('%ip' => $ip, '%ipurl' => $iplink, '%honeypot' => $link, '%whitelisturl' => url('httpbl/whitelist')));
    
    header('HTTP/1.1 403 Forbidden');
    print "<html>\n<body>\n";
    print $message . "\n";
    print "</body>\n</html>";
    exit();
  }
  else if ($blacklisted === TRUE && !_httpbl_whitelisted($ip)) {
    // blacklisted
    $message = variable_get('httpbl_message_black', "Sorry, %ip has been blacklisted by <a href=\"%ipurl\">http:BL</a>.\n%honeypot");
    if ($link = variable_get('httpbl_link', NULL)) {
      $word = variable_get('httpbl_word', 'randomness');
      $link = httpbl_honeylink($link, $word);
    }
    
    $message = strtr($message, array('%ip' => $ip, '%ipurl' => $iplink, '%honeypot' => $link));
    
    header('HTTP/1.1 403 Forbidden');
    print "<html>\n<body>\n";
    print $message . "\n";
    print "</body>\n</html>";
    exit();
  }
}

/**
 * Implementation of hook_help.
 *
 * @param $section string
 */
// function httpbl_help($section) {
//   switch ($section) {
//     case 'admin/settings/httpbl':
//      return t('For more information about http:BL, see <a href="http://www.projecthoneypot.org/httpbl.php">the http:BL homepage</a>.');
//      break;
//   }
// }

/**
 * Implementation of hook_settings().
 *
 * @return array
 */
function httpbl_admin_settings() {
  if (!$_POST && (!variable_get('httpbl_accesskey', NULL) || !variable_get('httpbl_check', 0))) {
    drupal_set_message(t('IP blacklist lookups are currently disabled; enter your access key below and enable checks to enable blacklist lookups.'), 'error');
  }
  
  $form['core'] = array(
    '#type' => 'fieldset', 
    '#title' => t('http:BL'),
    '#description' => t('For more information about http:BL, see the <a href="http://www.projecthoneypot.org/httpbl.php">http:BL homepage</a>.'),
    '#collapsible' => TRUE,
  );
  
  $form['core']['httpbl_accesskey'] = array(
    '#type' => 'textfield',
    '#title' => t('http:BL Access Key'),
    '#default_value' => variable_get('httpbl_accesskey', NULL),
    '#description' => t('Your http:BL <a href="http://www.projecthoneypot.org/httpbl_configure.php">Access Key</a>.'),
    '#size' => 20,
    '#maxlength' => 12,
  );
  
  $form['core']['httpbl_check'] = array(
    '#type' => 'select', 
    '#title' => t('Check blacklist status'), 
    '#default_value' => variable_get('httpbl_check', 0),
    '#options' => array(
      '0' => t('Nowhere (disabled)'), 
      // t('On comment, registration and contact forms'), 
      '2' => t('On all pages'),
    ),
    '#description' => t('At what times the blacklist should be checked.'),
  );
  
  $form['core']['httpbl_message_black'] = array(
    '#type' => 'textarea',
    '#title' => t('Blacklist message'),
    '#default_value' => variable_get('httpbl_message_black', "Sorry, %ip has been blacklisted by <a href=\"%ipurl\">http:BL</a>.\n%honeypot"),
    '#description' => t("The message visitors will see when their IP is blacklisted. <em>%ip</em> will be replaced with the visitor's IP, <em>%ipurl</em> with a link to the Project Honeypot information page for that IP, <em>%honeypot</em> with your Honeypot link."),
  );
  
  $form['core']['httpbl_message_grey'] = array(
    '#type' => 'textarea',
    '#title' => t('Greylist message'),
    '#default_value' => variable_get('httpbl_message_grey', "Sorry, %ip has been greylisted by <a href=\"%ipurl\">http:BL</a>.\nYou may try whitelisting on <a href=\"%whitelisturl\">%whitelisturl</a>.\n%honeypot"),
    '#description' => t("The message visitors will see when their IP is greylisted. <em>%ip</em> will be replaced with the visitor's IP, <em>%ipurl</em> with a link to the Project Honeypot information page for that IP, <em>%honeypot</em> with your Honeypot link, <em>%whitelisturl</em> with the whitelist request URL."),
  );
  
  $form['honeypot'] = array(
    '#type' => 'fieldset', 
    '#title' => t('Honeypot'),
    '#description' => t('Your Honeypot (spam trap) settings. For more information, see the <a href="http://www.projecthoneypot.org/">Project Honey Pot homepage</a>.'),
    '#collapsible' => TRUE,
  );
  
  $form['honeypot']['httpbl_footer'] = array(
    '#type' => 'checkbox',
    '#title' => t('Add link to footer'),
    '#default_value' => variable_get('httpbl_footer', FALSE),
    '#description' => t('Whether to add your Honeypot link to the footer of every page.'),
  );
  
  $form['honeypot']['httpbl_link'] = array(
    '#type' => 'textfield',
    '#title' => t('Project Honey Pot Link'),
    '#default_value' => variable_get('httpbl_link', NULL),
    '#description' => t('Your Honeypot (spam trap) link. This can be one of your own <a href="http://www.projecthoneypot.org/manage_honey_pots.php">Honey Pots</a> or a <a href="http://www.projecthoneypot.org/manage_quicklink.php">QuickLink</a>.'),
  );
  
  $form['honeypot']['httpbl_word'] = array(
    '#type' => 'textfield',
    '#title' => t('Link word'),
    '#default_value' => variable_get('httpbl_word', 'randomness'),
    '#description' => t('A random word which will be used as a link.'),
  );
  
  $form['advanced'] = array(
    '#type' => 'fieldset', 
    '#title' => t('Advanced'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  
  $form['advanced']['httpbl_threatlevel'] = array(
    '#type' => 'textfield',
    '#title' => t('Greylisting threat level threshold'),
    '#default_value' => variable_get('httpbl_threatlevel', 50),
    '#description' => t('Threshold for the greylisting threat level (1-255, 0 to disable)'),
    '#size' => 5,
    '#maxlength' => 3,
  );
  
  $form['advanced']['httpbl_logging'] = array(
    '#type' => 'select', 
    '#title' => t('Logging'), 
    '#default_value' => variable_get('httpbl_logging', 1),
    '#options' => array(
      t('Only errors'), 
      t('Blacklists'), 
      t('All requests (debugging)'),
    ),
    '#description' => t('Logging level for http:BL requests.'),
  );

  return system_settings_form($form);
}

/**
 * Form API callback to validate the httpbl settings form.
 */
function httpbl_admin_settings_validate($form_id, $form_values) {
  $key = $form_values['httpbl_accesskey'];
  
  if ($form_values['httpbl_check'] && !$key) {
    form_set_error('httpbl_accesskey', t('You must enter an access key to enable blacklist checks.'));
  }
  
  if ($form_values['httpbl_footer'] && !$form_values['httpbl_link']) {
    form_set_error('httpbl_link', t('You must enter a link to be able to add it to the footer.'));
  }
  
  if (!is_numeric($form_values['httpbl_threatlevel']) || $form_values['httpbl_threatlevel'] > 255 || $form_values['httpbl_threatlevel'] < 0) {
    form_set_error('httpbl_threatlevel', t('Threat level threshold should be a numeric value between 0 to 255.'));
  }
  
  if ($key) {
    // key should be 12 lowercase alpha characters
    if (ereg('[^a-z]', $key) || strlen($key) != 12) {
      form_set_error('httpbl_accesskey', t('Your access key is formatted incorrectly.'));
    }
    else if (!count(form_get_errors())) {
      // look up 127.80.1.1 as a test
      $lookup = httpbl_dnslookup('1.1.80.127', $key);
      if (!$lookup || $lookup['raw'] != '127.80.1.1') {
        form_set_error('httpbl_accesskey', t('Testcase failed. This either means that your access key is incorrect or that you have a problem in your DNS system.'));
      }
      else {
        drupal_set_message('http:BL test completed succesfully.');
      }
    }
  }

}

/**
 * Implementation of hook_menu().
 *
 * @return array
 */
function httpbl_menu($may_cache) {
  $items = array();

  if ($may_cache) {
    $items[] = array(
      'path' => 'httpbl/whitelist',
      'title' => t('Request whitelisting'),
      'callback' => 'drupal_get_form',
      'callback arguments' => array('httpbl_request_whitelist'),
      'type' => MENU_CALLBACK,
      'access' => TRUE,
    );
    $items[] = array(
      'path' => 'admin/settings/httpbl',
      'title' => t('http:BL'),
      'description' => t('Manage http:BL settings.'),
      'callback' => 'drupal_get_form',
      'callback arguments' => array('httpbl_admin_settings'),
      'access' => user_access('administer site configuration'),
      'type' => MENU_NORMAL_ITEM,
    );
  }
  return $items;
}

/**
 * Implementation of hook_footer().
 *
 * Adds a Project Honeypot link to the footer.
 */
function httpbl_footer($main = 0) {
  if (variable_get('httpbl_footer', FALSE)) {
    $link = variable_get('httpbl_link', NULL);
    $word = variable_get('httpbl_word', 'randomness');
    return httpbl_honeylink($link, $word);
  }
}

/**
 * Implementation of hook_cron().
 *
 * Cleans up cache table.
 */
function httpbl_cron() {
  db_query("DELETE FROM {httpbl} WHERE expire <= %d", time());
}

/**
 * Return HTML code with hidden Honeypot link
 *
 * @param string $link
 * @param string $word
 * @return string
 */
function httpbl_honeylink($link, $word) {
  if (!$link) {
    return;
  }
  $rand = (mt_rand(0,7));
  if ($rand == 0) {
    return '<div><a href="' . $link .  '"><!-- ' . $word . ' --></a></div>';
  }
  else if ($rand == 1) {
    return '<div><a href="' . $link .  '" style="display: none;">' . $word .  '</a></div>';
  }
  else if ($rand == 2) {
    return '<div style="display: none;"><a href="' . $link .  '">' . $word .  '</a></div>';
  }
  else if ($rand == 3) {
    return '<div><a href="' . $link .  '"></a></div>';
  }
  else if ($rand == 4) {
    return '<!-- <a href="' . $link .  '">' . $word .  '</a> -->';
  }
  else if ($rand == 5) {
    return '<div style="position: absolute; top: -250px; left: -250px;"><a href="' . $link .  '">' . $word .  '</a></div>';
  }
  else if ($rand == 6) {
    return '<div><a href="' . $link .  '"><span style="display: none;">' . $word .  '</span></a></div>';
  }
  else {
    return '<div><a href="' . $link .  '"><div style="height: 0px; width: 0px;"></div></a></div>';
  }
}

/**
 * Check if an IP should be banned
 * 
 * @param string $ip
 * @return bool
 */
 
function httpbl_blacklisted($ip = NULL) {
  $result = _httpbl_cache_get($ip);
  
  
  if ($result === NULL) {
    $key = variable_get('httpbl_accesskey', NULL);
    if ($key && $iprev = httpbl_reverse_ip($ip)) {
      if ($response = httpbl_dnslookup($iprev, $key)) {
        $iplink = '<a href="http://www.projecthoneypot.org/search_ip.php?ip=' . $ip . '">IP data</a>';
        // positive threat, type is positive (not search engine)
        if ($response['threat'] > variable_get('httpbl_threatlevel', 50) && $response['type']) {
          if (variable_get('httpbl_logging', 1)) {
            watchdog('httpbl', _httpbl_t('%ip was blacklisted (%response)', array('%ip' => $ip, '%response' => $response['raw'])), WATCHDOG_WARNING, $iplink);
          }
          _httpbl_cache_set($ip, 1, 7200);
          return TRUE;
        }
        else if ($response['threat'] && $response['type']) {
          if (variable_get('httpbl_logging', 1)) {
            watchdog('httpbl', _httpbl_t('%ip was greylisted (%response)', array('%ip' => $ip, '%response' => $response['raw'])), WATCHDOG_WARNING, $iplink);
          }
          _httpbl_cache_set($ip, 2, 7200);
          return 2;
        }
        else {
          if (variable_get('httpbl_logging', 1) > 1) {
            watchdog('httpbl', _httpbl_t('Lookup for %ip was negative (%response)', array('%ip' => $ip, '%response' => $response['raw'])), WATCHDOG_NOTICE, $iplink);
          }
           _httpbl_cache_set($ip, 0, 10800);
          return FALSE;
        }
      }
      else {
        if (variable_get('httpbl_logging', 1) > 1) {
          watchdog('httpbl', _httpbl_t('No results for %ip', array('%ip' => $ip)), WATCHDOG_NOTICE);
        }
         _httpbl_cache_set($ip, 0, 21600);
        return FALSE;
      }
    }
  }
  else {
    return $result;
  }
}

/**
 * Check if an IP is known to belong to a search engine
 * 
 * @param string $ip
 * @return bool
 */
 
function httpbl_se($ip = NULL) {
  $key = variable_get('httpbl_accesskey', NULL);
  if ($key && $iprev = httpbl_reverse_ip($ip)) {
    if ($response = httpbl_dnslookup($iprev, $key)) {
      $iplink = '<a href="http://www.projecthoneypot.org/search_ip.php?ip=' . $ip . '">IP data</a>';
      // positive threat, type is search engine (0)
      if ($response['threat'] && $response['type'] == 0) {
        if (variable_get('httpbl_logging', 1) > 1) {
          watchdog('httpbl', _httpbl_t('Search engine lookup for %ip was positive (%response)', array('%ip' => $ip, '%response' => $response['raw'])), WATCHDOG_NOTICE, $iplink);
        }
        return TRUE;
      }
      else {
        if (variable_get('httpbl_logging', 1) > 1) {
          watchdog('httpbl', _httpbl_t('Search engine lookup for %ip was negative (%response)', array('%ip' => $ip, '%response' => $response['raw'])), WATCHDOG_NOTICE, $iplink);
        }
        return FALSE;
      }
    }
    else {
      return FALSE;
    }
  }
}

/**
 * Reverse IP octets
 * 
 * @param string $ip
 * @return string
 */

function httpbl_reverse_ip($ip) {
  if (!is_numeric(str_replace('.', '', $ip))) {
    return NULL;
  }
  $ip = explode('.', $ip);

  if (count($ip) != 4) {
    return NULL;
  }
  
  return $ip[3] . '.' . $ip[2] . '.' . $ip[1] . '.' . $ip[0];
}

function httpbl_request_whitelist() {
  if (_httpbl_cache_get($_SERVER['REMOTE_ADDR']) !== 2 || $_SESSION['httpbl_whitelisted']) {
    drupal_access_denied();
    exit();
  }
  
  $form['#redirect'] = 'node';
  
  $form['reason'] = array(
    '#type' => 'textarea',
    '#title' => t('Reason for block'),
    '#size' => 60,
    '#required' => TRUE,
  );
  
  $form['block'] = array(
    '#type' => 'textfield',
    '#title' => t('Leave this blank'),
    '#size' => 10,
  );
  
  $form['leave'] = array(
    '#type' => 'textfield',
    '#size' => 30,
    '#attributes' => array('style' => 'display: none')
  );
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Whitelist request'),
  );
  
  return $form;
}

function httpbl_request_whitelist_validate($form_id, $form_values) {
  $ip = $_SERVER['REMOTE_ADDR'];
  $iplink = '<a href="http://www.projecthoneypot.org/search_ip.php?ip=' . $ip . '">IP data</a>';
  
  if ($form_values['block'] || $form_values['leave']) {
    _httpbl_cache_update($_SERVER['REMOTE_ADDR'], 1, 86400);
    if (variable_get('httpbl_logging', 1)) {
      watchdog('httpbl', t('%ip failed session whitelist request, blacklisted for 24 hours.', array('%ip' => $ip)), WATCHDOG_WARNING, $iplink);
    }
    print 'Whitelist request failed; your IP has been blacklisted for 24 hours.';
    exit();
  }
  
  if (variable_get('httpbl_logging', 1) > 1) {
    watchdog('httpbl', t('%ip tried a whitelist request', array('%ip' => $ip)), WATCHDOG_NOTICE, $iplink);
  }
}

function httpbl_request_whitelist_submit($form_id, $form_values) {
  $ip = $_SERVER['REMOTE_ADDR'];
  $iplink = '<a href="http://www.projecthoneypot.org/search_ip.php?ip=' . $ip . '">IP data</a>';
  
  if (variable_get('httpbl_logging', 1)) {
    watchdog('httpbl', t('Session from %ip whitelisted. Reason: @reason', array('%ip' => $ip, '@reason' => $form_values['reason'])), WATCHDOG_WARNING, $iplink);
  }
  drupal_set_message(t('The current session has been whitelisted.'));
  $_SESSION['httpbl_whitelisted'] = 1;
}

/**
 * Do http:BL DNS lookup
 * 
 * @param string $iprev
 * @param string $key
 * @return array
 */

function httpbl_dnslookup($iprev, $key) {
  // Thanks to J.Wesley2 at
  // http://www.projecthoneypot.org/board/read.php?f=10&i=1&t=1
  
  if (!$iprev) {
    return NULL;
  }
  
  $query = $key . '.' . $iprev . '.dnsbl.httpbl.org.';
  $response = gethostbyname($query);
  
  if ($response == $query) {
    // if the domain does not resolve then it will be the same thing we passed to gethostbyname
    return FALSE; 
  }
  
  $values = array();
  $values['raw'] = $response;
  $response = explode('.', $response);
  
  if ($response[0] != '127') {
    // if the first octet is not 127, the response should be considered invalid
    watchdog('httpbl', _httpbl_t('Lookup failed for %ip, response was %response', array('%ip' => $ip, '%response' => $values['raw'])), WATCHDOG_ERROR);
    return FALSE;
  }
  
  $values['last_activity'] = $response[1];
  $values['threat'] = $response[2];
  $values['type'] = $response[3];
  if ($response[3] == 0){
    //if it's 0 then there's only 1 thing it can be
    $values['search_engine'] = TRUE;
  }

  if ($response[3] & 1){
    //does it have the same bits as 1 set
    $values['suspicious'] = TRUE;
  }

  if ($response[3] & 2){
    //does it have the same bits as 2 set
    $values['harvester'] = TRUE;
  }

  if ($response[3] & 4){
    //does it have the same bits as 4 set
    $values['comment_spammer'] = TRUE;
  }
  
  return $values;
}

/**
 * Check if an IP is whitelisted through the access table
 */
function _httpbl_whitelisted($ip) {
  return db_result(db_query_range("SELECT status FROM {access} WHERE type = 'host' AND LOWER('%s') LIKE LOWER(mask) ORDER BY status DESC", $ip, 0, 1)) == '1';
}

/**
 * Write status value into cache table
 */
function _httpbl_cache_set($ip, $status, $offset = 0) {
  db_query("INSERT IGNORE INTO {httpbl} (hostname, status, expire) VALUES ('%s', %d, %d)", $ip, $status, time() + $offset);
}

/**
 * Update cache table
 */
function _httpbl_cache_update($ip, $status, $offset = 0) {
  db_query("UPDATE {httpbl} SET status = %d, expire = %d WHERE hostname = '%s'", $status, time() + $offset, $ip);
}

/**
 * Get status value from cache table
 */
function _httpbl_cache_get($ip) {
  $result = db_result(db_query("SELECT status FROM {httpbl} WHERE hostname = '%s'", $ip));
  if ($result === '1') {
    return TRUE;
  }
  else if ($result === '0') {
    return FALSE;
  }
  else if ($result === '2') {
    return 2;
  }
}

/**
 * Implementation of t() in case 'the real thing' is not loaded,
 * e.g. when a cached page is returned.
 */
function _httpbl_t($string, $args = 0) { 
  global $locale; 
  if (function_exists('t')) { 
    return t($string, $args);
  }
  if (!$args) { 
    return $string; 
  }
  else { 
    // Transform arguments before inserting them 
    foreach ($args as $key => $value) { 
      switch ($key[0]) { 
        // Escaped only 
        case '@': 
          $args[$key] = check_plain($value); 
        break; 
        // Escaped and placeholder 
        case '%': 
        default: 
          $args[$key] = '<em>' . check_plain($value) . '</em>'; 
          break; 
        // Pass-through 
        case '!': 
      } 
    } 
    return strtr($string, $args); 
  } 
}