# Bulk action configurations Evaluated Hosts admin view.

action.configuration.host_multiple_ban_action:
  type: action_configuration_default
  label: 'Blacklist and Ban host(s)'

action.configuration.host_multiple_delete_action:
  type: action_configuration_default
  label: 'Delete host(s)'

action.configuration.host_multiple_greylist_action:
  type: action_configuration_default
  label: 'Grey-list host(s)'

action.configuration.host_multiple_refresh_action:
  type: action_configuration_default
  label: 'Refresh Host Expiry'

action.configuration.host_multiple_unban_blacklisted_action:
  type: action_configuration_default
  label: 'Unban Blacklisted host(s)'

action.configuration.host_multiple_whitelist_action:
  type: action_configuration_default
  label: 'White-list host(s)'
