# Schema for the configuration files of the HttpBL module.

httpbl.settings:
  type: config_object
  label: 'HttpBL settings'
  mapping:
    core:
      type: mapping
      label: 'Core Requirements'
      mapping:
        httpbl_accesskey:
          type: string
          label: 'http:BL Access Key'
        httpbl_check:
          type: integer
          label: 'Check Level'
    honeypot:
      type: mapping
      label: 'Honeypots'
      mapping:
        httpbl_footer:
          type: boolean
          label: 'Add link to footer'
        httpbl_link:
          type: string
          label: 'Honeypot Link'
        httpbl_word:
          type: string
          label: 'Honeypot Link Word'
    advanced:
      type: mapping
      label: 'Logs, stats, thresholds and storage settings'
      mapping:
        httpbl_log:
          type: integer
          label: 'Logging'
        httpbl_stats:
          type: boolean
          label: 'Enable Stats'
        httpbl_storage:
          type: integer
          label: 'Results Storing'
        httpbl_black_threshold:
          type: integer
          label: 'Blacklisting Threshhold'
        httpbl_message_black:
          type: string
          label: 'Blacklist message'
        httpbl_grey_threshold:
          type: integer
          label: 'Greylisting Threshhold'
        httpbl_message_black:
          type: string
          label: 'Greylist message'
        httpbl_safe_offset:
          type: integer
          label: 'Safe Visitor Storage Expiry'
        httpbl_greylist_offset:
          type: integer
          label: 'Greylist Storage Expiry'
        httpbl_blacklist_offset:
          type: integer
          label: 'Blacklist Storage Expiry'
